//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.31 at 09:53:26 PM CET 
//


package com.nyx.mower.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for gardener complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="gardener">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="path" type="{}path"/>
 *         &lt;element name="mower" type="{}mower"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gardener", propOrder = {
        "path",
        "mower"
})
public class Gardener {

    @XmlList
    @XmlElement(required = true)
    protected List<Move> path;
    @XmlElement(required = true)
    protected Mower mower;

    /**
     * Gets the value of the path property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the path property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPath().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Move }
     */
    public List<Move> getPath() {
        if (path == null) {
            path = new ArrayList<Move>();
        }
        return this.path;
    }

    /**
     * Gets the value of the mower property.
     *
     * @return possible object is
     * {@link Mower }
     */
    public Mower getMower() {
        return mower;
    }

    /**
     * Sets the value of the mower property.
     *
     * @param value allowed object is
     *              {@link Mower }
     */
    public void setMower(Mower value) {
        this.mower = value;
    }

}
