//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.10 at 10:30:36 AM CEST 
//

package com.nyx.mower.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for move.
 * <p>
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * <p>
 * <pre>
 * &lt;simpleType name="move">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="D"/>
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="A"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "move")
@XmlEnum
public enum Move {

    D {
        @Override
        public void move(Mower mower) {
            mower.turnToRight();
        }
    },
    G {
        @Override
        public void move(Mower mower) {
            mower.turnToLeft();
        }
    },
    A {
        @Override
        public void move(Mower mower) {
            mower.forward();
        }
    };

    public abstract void move(Mower mower);
}
