//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.10 at 10:30:36 AM CEST 
//


package com.nyx.mower.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lawn" type="{}lawn"/>
 *         &lt;element name="mowers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="mower" type="{}mower" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lawn",
    "mowers"
})
@XmlRootElement(name = "mowitnow")
public class Mowitnow {

    @XmlElement(required = true)
    protected Lawn lawn;
    @XmlElement(required = true)
    protected Mowitnow.Mowers mowers;

    /**
     * Gets the value of the lawn property.
     * 
     * @return
     *     possible object is
     *     {@link Lawn }
     *     
     */
    public Lawn getLawn() {
        return lawn;
    }

    /**
     * Sets the value of the lawn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lawn }
     *     
     */
    public void setLawn(Lawn value) {
        this.lawn = value;
    }

    /**
     * Gets the value of the mowers property.
     * 
     * @return
     *     possible object is
     *     {@link Mowitnow.Mowers }
     *     
     */
    public Mowitnow.Mowers getMowers() {
        return mowers;
    }

    /**
     * Sets the value of the mowers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mowitnow.Mowers }
     *     
     */
    public void setMowers(Mowitnow.Mowers value) {
        this.mowers = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="mower" type="{}mower" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mower"
    })
    public static class Mowers {

        protected List<Mower> mower;

        /**
         * Gets the value of the mower property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the mower property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMower().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Mower }
         * 
         * 
         */
        public List<Mower> getMower() {
            if (mower == null) {
                mower = new ArrayList<Mower>();
            }
            return this.mower;
        }

    }

}
